### ISSUE TITLE
Upgrade to postfix 3.5.23 or 3.7.9

### ISSUE THREAD

**Issue by DrMurx** [mailserver2/mailserver#60]
Postfix before 3.5.23 and 3.7.9 are affected by "SMTP Smuggling", see https://www.postfix.org/smtp-smuggling.html

@SaraSmiseth Would you mind to release a build with upgraded debian-mail-overlay?

**Comment by SaraSmiseth** [comment]
After merging #58 we can release a new image. But we have to fix the tests first.

**Comment by AndrewSav** [comment]
We are pulling postfix from debian repo, the current version there is 3.7.9 so we should be good after merging https://github.com/mailserver2/mailserver/pull/58

**Comment by diroots** [comment]
https://github.com/mailserver2/mailserver/actions/runs/7457756574/job/20290497408?pr=58#step:3:166 postfix 3.7.9 from bookworm-updates repo

**Comment by diroots** [comment]
@SaraSmiseth @AndrewSav the postfix page says that there are new settings to be defined to actually mitigate the SMTP smuggling : https://www.postfix.org/smtp-smuggling.html#long

```
    smtpd_forbid_bare_newline = yes
    smtpd_forbid_bare_newline_exclusions = $mynetworks
```

so i think an update to https://github.com/mailserver2/mailserver/blob/master/rootfs/etc/postfix/main.cf is needed in order to add these params to effectively enable this feature. 

or maybe advise to enable this feature using the overriding of postfix config https://github.com/mailserver2/mailserver#override-postfix-configuration

(tbh, idk what is best, to enable it by default or not)

**Comment by DrMurx** [comment]
Thanks for your great work, @SaraSmiseth , @AndrewSav & @diroots
